theme: jekyll-theme-cayman
title: Documentation officielle de Cogeo.
description: Découvre nos documentations API, Architecture et Front-End.
author: C0ZEN
author_email: geoffrey.testelin@gmail.com
permalink: pretty
homePageUrl: https://c0zen.github.io/Cogeo/
apiUrl: https://c0zen.github.io/Cogeo/api/about/
architectureUrl: https://c0zen.github.io/Cogeo/architecture/about/
frontEndUrl: https://c0zen.github.io/Cogeo/front-end/about/
paulUrl: https://github.com/paolovador
paulName: paolovador
benUrl: https://github.com/BenoitCompere
benName: BenoitCompere
