theme: jekyll-theme-cayman
title: Bienvenue sur la documentation officielle de Cogeo !
description: Vous trouverez toutes les informations liées à la réalisation de notre projet via nos documentations Front, API et Architecture.
author: C0ZEN
author_email: geoffrey.testelin@gmail.com
permalink: pretty
homePageUrl: https://c0zen.github.io/Cogeo/
