theme: jekyll-theme-cayman
title: Documentation officielle de Cogeo.
description: Découvre nos documentations API, Architecture et Front-End.
author: C0ZEN
author_email: geoffrey.testelin@gmail.com
permalink: pretty
homePageUrl: https://c0zen.github.io/Cogeo/
