# Theme configuration
theme: jekyll-theme-cayman
title: Documentation officielle de Cogeo.
description: Découvrer nos documentations sur l'Architecture, le Back-End et le Front-End.
author: C0ZEN
author_email: geoffrey.testelin@gmail.com
permalink: pretty

# Url
homePageUrl: https://c0zen.github.io/Cogeo/
backEndUrl: https://c0zen.github.io/Cogeo/back-end/about/
architectureUrl: https://c0zen.github.io/Cogeo/architecture/about/
frontEndUrl: https://c0zen.github.io/Cogeo/front-end/about/
baseUrl: https://c0zen.github.io/Cogeo/

# Users
paulUrl: https://github.com/paolovador
paulName: paolovador
benUrl: https://github.com/BenoitCompere
benName: BenoitCompere
